In [ ]:
import numpy as np
import copy




In [ ]:
X = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
X.shape

W = np.array([10,20,30])

Y = copy.deepcopy(X)
for i in range(0,X.shape[0]):
  Y[i,:] = X[i,:] + W

print(Y), print(' ')
print(X)


[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
 
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
Y = X + W
print(Y), print(' ')
print(X)

[[11 22 33]
 [12 23 34]
 [13 24 35]
 [14 25 36]]
 
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
w = np.array([-1,0,1,0],ndmin=2).T
X*w

array([[-1, -2, -3],
       [ 0,  0,  0],
       [ 3,  4,  5],
       [ 0,  0,  0]])

In [5]:
# Exercise
# 
# 1) create a list of integers from 0 to 8 (v)
# 2) reshape to a 3x3 matrix(M)
# 3) repeat that matrix to 9x3 (C) 
# 4) broadcast-multiply with initial vector (B)
#
import numpy as np

#v = np.array([0,1,2,3,4,5,6,7,8],ndmin=2)
v = np.array([0,1,2,3,4,5,6,7,8])

M = v.reshape((3,3))

C = np.tile(M,(3,1))

#B = C*v.T
B = C*np.reshape(v,(len(v),1))

print(v)
print(M)
print(C)
print(B)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]


In [ ]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`